apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: my-namespace
spec:
  hard:
    requests.cpu: "2"             # Total CPU requests in the namespace
    requests.memory: "4Gi"        # Total memory requests in the namespace
    limits.cpu: "4"               # Total CPU limits in the namespace
    limits.memory: "8Gi"          # Total memory limits in the namespace
    pods: "10"                    # Total number of pods
    services: "5"                 # Total number of services
    persistentvolumeclaims: "5"   # Total number of PersistentVolumeClaims
    configmaps: "10"              # Total number of ConfigMaps
    secrets: "10"                 # Total number of Secrets
